<?php
	use GitHubClient, GitHubCommit;

	class GitHubCommits extends WireData implements Module {
		protected $github;

		public static function getModuleInfo() {
			return array(
				'title' => 'GitHub Commits',
				'version' => 101,
				'summary' => "Interacts with GitHub's Commits API using GitHubConnector",
				'singular' => true,
				'autoload' => true,
				'requires' => array('GitHubConnector')
			);
		}

		public function init() {
			if (empty($this->github)) {
				$this->connect();
			}
		}

		public function get_client() {
			if (empty($this->github)) {
				$this->connect();
			}
			return $this->github;
		}

		public function connect() {
			$this->github = $this->wire('modules')->get('GitHubConnector')->get_client();
		}

		public function get_repolabels($owner, $repo) {
			return $this->github->issues->labels->listAllLabelsForThisRepository($owner, $repo);
		}
}
